Adding 2D strip geometry
brettviren/pochoir pull request #6
Opened 2021-04-21 14:54 UTC by rennney

Adding generator to make 2D strip geometry for the Ew calculation. The generator draws 2 planes coll/ind. There are two supported patterns: 1) with a hole in the middle of the strip 2) holes are on each side of the strip

conf parameter in the generator is not yet utilized. Thus, all of the parameters are hardcoded and code works with only provided domain

2021-04-21 19:01 UTC, brettviren commented on pochoir/gen_pcb_2Dstrips.py
> +    Nstrips = 21 # total number of strips
These should be provided by cfg.

2021-04-21 19:05 UTC, brettviren requested changes
If it is more convenient to change these after a merge, let me know.  Otherwise, you can push more commits to this PR.

2021-04-21 19:05 UTC, brettviren commented on pochoir/gen_pcb_quarter.py
> +    draw_3D_pcb(arr,dom.shape,41,41,2000,0,-15000,100)
Also, these "magic" numbers should come from `cfg` and/or `dom`.

2021-04-22 14:52 UTC, rennney commented
I moved all hard-coded parameters to specific JSON files. Examples of such files are added in the test directory.

2021-04-22 14:52 UTC, closed without merging